---

- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: p4 -V
      ansible.builtin.shell: |
        set -euxo pipefail
        p4 -V
      args:
        executable: "/bin/bash"
      register: result
      changed_when: result is not succeeded
